import { EmissionFactor } from '../models/EmissionFactor.js'
import { logger } from './logger.js'

const baseFactors = [
  // --- ELECTRICITY ---
  {
    category: 'electricity',
    subCategory: 'national_grid',
    activity: 'grid_consumption',
    key: 'electricity_grid',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.00071, // 0.71 kg CO2/kWh converted to tons
    value: 0.00071,
    unit: 'tons/kWh',
    source: 'Central Electricity Authority (CEA) v19',
    publicationYear: 2023,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'Weighted average emission factor of grid connect power plants including renewables.',
    isActive: true,
  },
  {
    category: 'electricity',
    subCategory: 'state_grid',
    activity: 'grid_consumption',
    key: 'electricity_grid_MH',
    fuelType: null,
    vehicleClass: null,
    state: 'Maharashtra',
    country: 'IN',
    factor: 0.00079, // higher coal mix
    value: 0.00079,
    unit: 'tons/kWh',
    source: 'Central Electricity Authority (CEA) v19',
    publicationYear: 2023,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'State grid emissions derived from regional coal-dominant generation parameters.',
    isActive: true,
  },
  {
    category: 'electricity',
    subCategory: 'state_grid',
    activity: 'grid_consumption',
    key: 'electricity_grid_DL',
    fuelType: null,
    vehicleClass: null,
    state: 'Delhi',
    country: 'IN',
    factor: 0.00073,
    value: 0.00073,
    unit: 'tons/kWh',
    source: 'Central Electricity Authority (CEA) v19',
    publicationYear: 2023,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'State grid emissions derived from regional utility supply parameters.',
    isActive: true,
  },
  {
    category: 'electricity',
    subCategory: 'renewable',
    activity: 'solar_generation',
    key: 'electricity_solar',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.000048,
    value: 0.000048,
    unit: 'tons/kWh',
    source: 'Bureau of Energy Efficiency (BEE)',
    publicationYear: 2023,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'Lifecycle emissions including panel manufacturing and installation footprint.',
    isActive: true,
  },

  // --- TRANSPORTATION (ROAD) ---
  {
    category: 'transport',
    subCategory: 'road_transport',
    activity: 'passenger_car',
    key: 'transport_car_gasoline', // maps to gasoline input enum
    fuelType: 'gasoline',
    vehicleClass: 'sedan',
    state: null,
    country: 'IN',
    factor: 0.000143, // 143g CO2e/km converted to tons/km (US EPA / ARAI baseline)
    value: 0.000143,
    unit: 'tons/km',
    source: 'ARAI / MoRTH Guidelines',
    publicationYear: 2022,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'ARAI drive-cycle carbon diagnostics for standard passenger petrol sedans.',
    isActive: true,
  },
  {
    category: 'transport',
    subCategory: 'road_transport',
    activity: 'passenger_car',
    key: 'transport_car_diesel',
    fuelType: 'diesel',
    vehicleClass: 'sedan',
    state: null,
    country: 'IN',
    factor: 0.000135,
    value: 0.000135,
    unit: 'tons/km',
    source: 'ARAI / MoRTH Guidelines',
    publicationYear: 2022,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'ARAI drive-cycle carbon diagnostics for standard passenger diesel sedans.',
    isActive: true,
  },
  {
    category: 'transport',
    subCategory: 'road_transport',
    activity: 'passenger_car',
    key: 'transport_car_hybrid',
    fuelType: 'hybrid',
    vehicleClass: 'sedan',
    state: null,
    country: 'IN',
    factor: 0.000095,
    value: 0.000095,
    unit: 'tons/km',
    source: 'ARAI / MoRTH Guidelines',
    publicationYear: 2022,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'Evaluation of strong hybrid power splits under city driving conditions.',
    isActive: true,
  },
  {
    category: 'transport',
    subCategory: 'road_transport',
    activity: 'passenger_car',
    key: 'transport_car_electric',
    fuelType: 'electric',
    vehicleClass: 'sedan',
    state: null,
    country: 'IN',
    factor: 0.000055,
    value: 0.000055,
    unit: 'tons/km',
    source: 'ARAI / MoRTH Guidelines',
    publicationYear: 2022,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'Scope 2 indirect charging emissions based on standard Indian national grid mix.',
    isActive: true,
  },
  {
    category: 'transport',
    subCategory: 'road_transport',
    activity: 'motorcycle',
    key: 'transport_motorcycle',
    fuelType: 'petrol',
    vehicleClass: 'motorcycle',
    state: null,
    country: 'IN',
    factor: 0.000045,
    value: 0.000045,
    unit: 'tons/km',
    source: 'ARAI Guidelines',
    publicationYear: 2022,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'ARAI standards for small displacement 2-wheelers.',
    isActive: true,
  },

  // --- PUBLIC TRANSPORT ---
  {
    category: 'transport',
    subCategory: 'public_transport',
    activity: 'metro_rail',
    key: 'transport_transit', // mapped to transit hours
    fuelType: 'electric',
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.000015, // per passenger-km equivalent or generic hour
    value: 0.000015,
    unit: 'tons/km',
    source: 'Indian Railways / Delhi Metro (DMRC)',
    publicationYear: 2022,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'Electric traction metrics divided by average occupancy rates per coach.',
    isActive: true,
  },
  {
    category: 'transport',
    subCategory: 'public_transport',
    activity: 'domestic_flight',
    key: 'transport_flight',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.115, // tons/hour
    value: 0.115,
    unit: 'tons/hour',
    source: 'Directorate General of Civil Aviation (DGCA) India',
    publicationYear: 2023,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'Aviation turbine fuel consumption models adjusted for regional Indian airports.',
    isActive: true,
  },

  // --- HOUSEHOLD ENERGY ---
  {
    category: 'gas',
    subCategory: 'household_energy',
    activity: 'lpg_combustion',
    key: 'gas_combustion', // maps to gas_combustion input key
    fuelType: 'lpg',
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.00298, // tons per kg or cylinder units
    value: 0.00298,
    unit: 'tons/kg',
    source: 'Ministry of Petroleum & Natural Gas (PPAC)',
    publicationYear: 2023,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'Stoichiometric combustion values for commercial grade propane/butane mixes.',
    isActive: true,
  },

  // --- FOOD ---
  {
    category: 'food',
    subCategory: 'dietary_pattern',
    activity: 'meat_heavy_diet',
    key: 'food_diet_meat-heavy',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 3.3,
    value: 3.3,
    unit: 'tons/year',
    source: 'IPCC Guidelines / Indian Diet Survey',
    publicationYear: 2019,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'IPCC food lifecycle defaults adapted to Indian grain-and-dairy intensive dietary grids.',
    isActive: true,
  },
  {
    category: 'food',
    subCategory: 'dietary_pattern',
    activity: 'balanced_diet',
    key: 'food_diet_balanced',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 2.2,
    value: 2.2,
    unit: 'tons/year',
    source: 'IPCC Guidelines / Indian Diet Survey',
    publicationYear: 2019,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'IPCC food lifecycle defaults adapted to Indian dietary grids.',
    isActive: true,
  },
  {
    category: 'food',
    subCategory: 'dietary_pattern',
    activity: 'vegetarian_diet',
    key: 'food_diet_vegetarian',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 1.5,
    value: 1.5,
    unit: 'tons/year',
    source: 'IPCC Guidelines / Indian Diet Survey',
    publicationYear: 2019,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'Lacto-vegetarian dietary lifecycle footprints representing typical Indian diets.',
    isActive: true,
  },
  {
    category: 'food',
    subCategory: 'dietary_pattern',
    activity: 'vegan_diet',
    key: 'food_diet_vegan',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 1.2,
    value: 1.2,
    unit: 'tons/year',
    source: 'IPCC Guidelines / Indian Diet Survey',
    publicationYear: 2019,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'Plant-based diet defaults without dairy/animal proteins.',
    isActive: true,
  },

  // --- WASTE ---
  {
    category: 'waste',
    subCategory: 'landfill',
    activity: 'mixed_organic_waste',
    key: 'waste_landfill_bag',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.052,
    value: 0.052,
    unit: 'tons/bag',
    source: 'Central Pollution Control Board (CPCB) India',
    publicationYear: 2021,
    version: 'IN-2023-V1.0',
    confidence: 'Medium',
    methodology: 'Average wet and dry municipal waste decomposition ratios under local temperature averages.',
    isActive: true,
  },

  // --- WATER ---
  {
    category: 'water',
    subCategory: 'municipal_supply',
    activity: 'water_filtration',
    key: 'water_consumption',
    fuelType: null,
    vehicleClass: null,
    state: null,
    country: 'IN',
    factor: 0.0003,
    value: 0.0003,
    unit: 'tons/Litre',
    source: 'Central Pollution Control Board (CPCB) India',
    publicationYear: 2021,
    version: 'IN-2023-V1.0',
    confidence: 'High',
    methodology: 'Electricity overhead calculations for municipal pumping and water treatment plants.',
    isActive: true,
  },
]

export const seedFactors = async () => {
  try {
    // Clear and re-populate the collection on seed to ensure clean structure with new fields
    await EmissionFactor.deleteMany({})
    await EmissionFactor.insertMany(baseFactors)
    logger.info('🌱 Database successfully seeded with production-ready Indian carbon emission factors.')
  } catch (error) {
    logger.error(`❌ Seeding Error: ${error instanceof Error ? error.message : String(error)}`)
  }
}

export default seedFactors
